In [1]:
import numpy as np
import tensorflow as tf

/Users/jeremy.zhang/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/Users/jeremy.zhang/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.enable_eager_execution()

In [3]:
tf.__version__

'1.10.1'

In [4]:
points = tf.random_normal([100])

In [8]:
points

<tf.Tensor: id=6, shape=(100,), dtype=float32, numpy=
array([-2.6373684 ,  0.68251127, -0.63200223,  0.15978476,  0.8975377 ,
        0.5704441 , -0.10744245, -0.412299  , -0.11914694,  1.6319933 ,
       -0.5060321 ,  0.9759271 ,  0.27677086,  0.58321613,  0.5145135 ,
        1.9828728 ,  2.3749485 ,  0.34434387,  0.8598209 ,  0.4907976 ,
        1.293161  ,  0.14451589,  0.43540916, -0.99616057, -0.07271417,
       -0.5352724 ,  0.1574582 ,  0.3475846 ,  1.1604266 , -1.1990631 ,
       -0.6547631 , -2.8029656 , -0.18988948, -0.85334736, -0.54024017,
        0.19599965, -0.76379377,  0.42538303, -0.25873882,  1.7287139 ,
        0.44178054,  1.1487643 , -1.5717676 ,  0.24684285, -1.6064228 ,
       -0.32840744,  1.6060942 ,  1.4377952 , -0.7040763 , -0.8967659 ,
       -0.44592848,  0.6165078 ,  1.0207105 , -1.6279761 ,  0.26737022,
       -0.12546167, -1.5921247 , -0.06731059, -0.8801808 ,  0.664726  ,
        1.6632204 , -0.35664764,  0.05954761,  0.40504873,  0.5308658 ,
       -0.

### K-Means clustering example

In [9]:
num_points = 100
dimensions = 2
points = np.random.uniform(0, 1000, [num_points, dimensions])

In [10]:
points.shape

(100, 2)

In [11]:
def input_fn():
    return tf.train.limit_epochs(tf.convert_to_tensor(points, dtype=tf.float32), num_epochs=1)

In [12]:
num_clusters = 5
kmeans = tf.contrib.factorization.KMeansClustering(num_clusters=num_clusters, use_mini_batch=False)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmp1bp7q1yf', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1c25899940>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [13]:
# train
num_iterations = 10
previous_centers = None
for _ in range(num_iterations):
    kmeans.train(input_fn)
    cluster_centers = kmeans.cluster_centers()
    if previous_centers is not None:
        print('delta:', cluster_centers - previous_centers)
    previous_centers = cluster_centers
    print('score:', kmeans.score(input_fn))
print('cluster centers:', cluster_centers)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmp1bp7q1yf/model.ckpt.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmp1bp7q1yf/model.ckpt.
INFO:tensorflow:Loss for final step: None.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-02-25-08:27:54
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmp1bp7q1yf/model.ckpt-1
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2019-02-25-08:27:55
INFO:tensorflow:Saving

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-02-25-08:27:59
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmp1bp7q1yf/model.ckpt-11
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2019-02-25-08:27:59
INFO:tensorflow:Saving dict for global step 11: global_step = 11, loss = 3617961.8, score = 3617961.8
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 11: /var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmp1bp7q1yf/model.ckpt-11
score: 3617961.8
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmp1bp7q1yf/model.ckpt-11
INFO:tensorflow:Running local_init_op.


In [14]:
cluster_indices = list(kmeans.predict_cluster_index(input_fn))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmp1bp7q1yf/model.ckpt-19
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [15]:
np.unique(cluster_indices)

array([0, 1, 2, 3, 4])

In [33]:
cluster_centers

array([[720.31586, 227.36775],
       [216.61801, 805.15173],
       [129.26576, 189.25955],
       [316.92072, 409.86215],
       [743.432  , 691.5111 ]], dtype=float32)

#### TF

In [34]:
tf_points = tf.random_normal([100, 2])

In [39]:
num_clusters = 5
kmeans = tf.contrib.factorization.KMeansClustering(num_clusters=num_clusters, use_mini_batch=False)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmpx44gzjin', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1c2e9fe470>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [67]:
def input():
    return tf.train.limit_epochs(tf.convert_to_tensor(points, dtype=tf.float32), num_epochs=1)

In [68]:
kmeans.train(input)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmpx44gzjin/model.ckpt-3
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 3 into /var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmpx44gzjin/model.ckpt.
INFO:tensorflow:loss = 3859562.2, step = 4
INFO:tensorflow:Saving checkpoints for 5 into /var/folders/hr/v0bnx1zn69v4_7dmyfd2n4gh0000gn/T/tmpx44gzjin/model.ckpt.
INFO:tensorflow:Loss for final step: 3859562.2.


In [65]:
with tf.Session():
    a = tf.convert_to_tensor(points, dtype=tf.float32)
    print(a.eval()[:3])

[[811.1301  196.88359]
 [405.62537 716.32947]
 [615.97974 423.1539 ]]
